# Generated by Django 2.2.20 on 2021-08-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('tc', models.CharField(max_length=11, null=True, unique=True)),
                ('city', models.CharField(max_length=15, null=True)),
                ('district', models.CharField(max_length=15, null=True)),
                ('telephone', models.CharField(max_length=11, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
