# Generated by Django 3.2.5 on 2021-07-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210715_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazı',
            name='yayinTarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
