# Generated by Django 3.2.5 on 2021-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_yazı_yayintarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazı',
            name='Cıty',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='yazı',
            name='District',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='yazı',
            name='TC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yazı',
            name='Telephone',
            field=models.IntegerField(null=True),
        ),
    ]
