# Generated by Django 3.2.5 on 2021-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_yazı_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazı',
            name='TC',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
