# Generated by Django 3.2.5 on 2021-07-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_newcustomer_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='TC',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newcustomer',
            name='Telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
