# Generated by Django 3.2.5 on 2021-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yazı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=120)),
                ('metin', models.TextField()),
                ('yayınTarihi', models.DateTimeField()),
            ],
        ),
    ]
