# Generated by Django 3.2.5 on 2021-07-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazı',
            old_name='yayınTarihi',
            new_name='KayıtTarihi',
        ),
        migrations.RenameField(
            model_name='yazı',
            old_name='başlık',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='yazı',
            old_name='metin',
            new_name='Surname',
        ),
    ]
