# Generated by Django 3.2.5 on 2021-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210715_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazı',
            old_name='KayıtTarihi',
            new_name='yayinTarihi',
        ),
        migrations.AlterField(
            model_name='yazı',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='yazı',
            name='Surname',
            field=models.CharField(max_length=20),
        ),
    ]
