# Generated by Django 3.2.5 on 2021-07-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210716_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazı',
            old_name='Cıty',
            new_name='City',
        ),
    ]
