# Generated by Django 3.2.5 on 2021-07-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_cıty_yazı_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazı',
            name='City',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
