# Generated by Django 3.2.5 on 2021-07-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_yazı_tc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yazı',
            new_name='NewCustomer',
        ),
    ]
