# Generated by Django 3.2.5 on 2021-07-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_yazı_newcustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcustomer',
            old_name='yayinTarihi',
            new_name='Date',
        ),
    ]
