# Generated by Django 3.2.5 on 2021-07-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_rename_date_newcustomer_yayintarihi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcustomer',
            old_name='yayinTarihi',
            new_name='Date',
        ),
    ]
