# Generated by Django 3.2.5 on 2021-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_rename_yayintarihi_newcustomer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='Telephone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
